#ifndef TOKENS_HPP
#define TOKENS_HPP

#include <vector>

#include <unordered_map>

enum TokenType
{
    TOKEN_INT,
    TOKEN_BOOL,
    TOKEN_CHAR,
    TOKEN_STRING,

    TOKEN_TYPE_INT,
    TOKEN_TYPE_BOOL,
    TOKEN_TYPE_CHAR,
    TOKEN_TYPE_STRING,
    TOKEN_TYPE_MEMPTR,

    TOKEN_CAST,

    TOKEN_ADD,
    TOKEN_SUBTRACT,
    TOKEN_MULTIPLY,
    TOKEN_DIVIDE,
    TOKEN_MOD,

    TOKEN_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS_EQUAL,

    TOKEN_INVERT,
    TOKEN_LNOT,
    TOKEN_LAND,
    TOKEN_LOR,
    TOKEN_RSHIFT,
    TOKEN_LSHIFT,

    TOKEN_READ_MEMORY_32,
    TOKEN_WRITE_MEMORY_32,
    TOKEN_ADD_WRITE_MEMORY_32,
    TOKEN_SUBTRACT_WRITE_MEMORY_32,
    TOKEN_MULTIPLY_WRITE_MEMORY_32,
    TOKEN_DIVIDE_WRITE_MEMORY_32,

    TOKEN_READ_MEMORY_8,
    TOKEN_WRITE_MEMORY_8,
    TOKEN_ADD_WRITE_MEMORY_8,
    TOKEN_SUBTRACT_WRITE_MEMORY_8,
    TOKEN_MULTIPLY_WRITE_MEMORY_8,
    TOKEN_DIVIDE_WRITE_MEMORY_8,

    TOKEN_CR,
    TOKEN_PRINT,
    TOKEN_DOT,

    TOKEN_INPUT,

    TOKEN_DUP,
    TOKEN_DROP,
    TOKEN_SWAP,
    TOKEN_OVER,
    TOKEN_ROT,

    TOKEN_MEM,
    TOKEN_ENDMEM,

    TOKEN_CONST,
    TOKEN_CALL_CONST,

    TOKEN_CREATE_VAR,
    TOKEN_VAR,

    TOKEN_MACRO,
    TOKEN_ENDMACRO,

    TOKEN_IF,
    TOKEN_THEN,
    TOKEN_ELSEIF,
    TOKEN_ELSE,
    TOKEN_ENDIF,

    TOKEN_WHILE,
    TOKEN_DO,
    TOKEN_ENDWHILE,

    TOKEN_FUNC,
    TOKEN_CALLFUNC,
    TOKEN_DEFINE,
    TOKEN_FUNC_SEPERATOR,
    TOKEN_ENDFUNC,

    TOKEN_INCLUDE,

    TOKEN_COUNT
};

const std::vector<const char*> TokenString
{
    "TOKEN_INT",
    "TOKEN_BOOL",
    "TOKEN_CHAR",
    "TOKEN_STRING",

    "TOKEN_TYPE_INT",
    "TOKEN_TYPE_BOOL",
    "TOKEN_TYPE_CHAR",
    "TOKEN_TYPE_STRING",
    "TOKEN_TYPE_MEMPTR",

    "TOKEN_CAST",

    "TOKEN_ADD",
    "TOKEN_SUBTRACT",
    "TOKEN_MULTIPLY",
    "TOKEN_DIVIDE",
    "TOKEN_MOD",

    "TOKEN_EQUAL",
    "TOKEN_NOT_EQUAL",
    "TOKEN_GREATER",
    "TOKEN_LESS",
    "TOKEN_GREATER_EQUAL",
    "TOKEN_LESS_EQUAL",

    "TOKEN_INVERT",
    "TOKEN_LNOT",
    "TOKEN_LAND",
    "TOKEN_LOR",
    "TOKEN_RSHIFT",
    "TOKEN_LSHIFT",

    "TOKEN_READ_MEMORY_32",
    "TOKEN_WRITE_MEMORY_32",
    "TOKEN_ADD_WRITE_MEMORY_32",
    "TOKEN_SUBTRACT_WRITE_MEMORY_32",
    "TOKEN_MULTIPLY_WRITE_MEMORY_32",
    "TOKEN_DIVIDE_WRITE_MEMORY_32",

    "TOKEN_READ_MEMORY_8",
    "TOKEN_WRITE_MEMORY_8",
    "TOKEN_ADD_WRITE_MEMORY_8",
    "TOKEN_SUBTRACT_WRITE_MEMORY_8",
    "TOKEN_MULTIPLY_WRITE_MEMORY_8",
    "TOKEN_DIVIDE_WRITE_MEMORY_8",

    "TOKEN_CR",
    "TOKEN_PRINT",
    "TOKEN_DOT",

    "TOKEN_INPUT",

    "TOKEN_DUP",
    "TOKEN_DROP",
    "TOKEN_SWAP",
    "TOKEN_OVER",
    "TOKEN_ROT",

    "TOKEN_MEM",
    "TOKEN_ENDMEM",

    "TOKEN_CONST",
    "TOKEN_CALL_CONST",

    "TOKEN_CREATE_VAR",
    "TOKEN_VAR",

    "TOKEN_MACRO",
    "TOKEN_ENDMACRO",

    "TOKEN_IF",
    "TOKEN_THEN",
    "TOKEN_ELSEIF",
    "TOKEN_ELSE",
    "TOKEN_ENDIF",

    "TOKEN_WHILE",
    "TOKEN_DO",
    "TOKEN_ENDWHILE",

    "TOKEN_FUNC",
    "TOKEN_CALLFUNC",
    "TOKEN_DEFINE",
    "TOKEN_FUNC_SEPERATOR",
    "TOKEN_ENDFUNC",

    "TOKEN_INCLUDE",
};

struct Token
{
    TokenType type;
    size_t sourceIndex;
    size_t line;
    size_t column;
    char* startIndex;
    char* endIndex;
};

#endif
